server:
  port: 7011
  servlet:
    context-path: /api

spring:
  application:
    name: dubbo-nacos-order
dubbo:
  application:
    name: order-app
    qos-enable: false
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://121.36.105.55:8848
  consumer:
    check: false
    retries: 2

