server:
  port: 7012
  servlet:
    context-path: /api

spring:
  application:
    name: dubbo-nacos-deliver
dubbo:
  application:
    name: deliver-app
    qos-enable: false
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://121.36.105.55:8848
  consumer:
    check: false

